SELECT 'MR.'|| ENAME ||'YOU HIERED ON '||HIREDATE || 'IN DEPTNO'|| DEPTNO
FROM SCOTT.EMP;

SELECT 'OYE ' ||ENAME || ' YOUR SALARY IS RS. ' || SAL ||'AND COMMISION IS ' || COMM
FROM SCOTT.EMP;
 
 --2
SELECT 'HEY! ' ||ENAME || ' YOUR WORKING AS  '||JOB || 'IN DEPTNO '|| DEPTNO
FROM SCOTT.EMP;

SELECT ' SORRY '||  ENAME || ' YOUR SAL IS RS. '|| SAL || 'AND WE ARE DEDUCTING 100 RPS IN IT FOR THAT YOU WILL GET JUST '|| (SAL-100) AS SALARY
FROM SCOTT.EMP;