--1  WAQTD SMITH'S REPORTING MANAGER NAME. 
SELECT  ENAME
FROM  SCOTT.EMP
WHERE  EMPNO IN(SELECT MGR
                  FROM SCOTT.EMP
                  WHERE ENAME = 'SMITH')

--2 WAQTD MILLER'S MANAGER'S SALARY.
SELECT SAL
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR
           FROM SCOTT.EMP
           WHERE ENAME = 'MILLER');

--3  WAQTD ALLEN'S MANAGER NAME.

SELECT ENAME 
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR
                FROM SCOTT.EMP
                WHERE ENAME = 'ALLEN');

--4 WAQTD SALARY OF ADAMS MANAGER. 
SELECT SAL
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR
                FROM SCOTT.EMP
                WHERE ENAME = 'ADAMS');

--5 WAQTD NAME OF ADAM'S MANAGER'S MANAGER. 
SELECT ENAME
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR 
                FROM SCOTT.EMP
                WHERE EMPNO IN
               (SELECT MGR
                FROM SCOTT.EMP
                WHERE ENAME = 'ADAMS'));

--6  SIR ADDED DNAME INSTED OF LOC
SELECT LOC 
FROM SCOTT.DEPT
WHERE DEPTNO IN
                (SELECT  DEPTNO
                   FROM SCOTT.EMP
                     WHERE EMPNO IN(SELECT MGR 
                FROM SCOTT.EMP
                WHERE EMPNO IN
               (SELECT MGR
                FROM SCOTT.EMP
                WHERE ENAME = 'SMITH')));

--7 WAQTD NUMBER OF EMP'S REPORTING TO KING 
SELECT COUNT(*)
FROM SCOTT.EMP
                WHERE MGR IN
               (SELECT EMPNO
                FROM SCOTT.EMP
                WHERE ENAME = 'KING');

--8 WAQTD NAME OF AN EMP REPORTING TO BLAKE. 
SELECT ENAME
FROM SCOTT.EMP
                WHERE MGR IN
               (SELECT EMPNO
                FROM SCOTT.EMP
                WHERE ENAME = 'BLAKE');

--9 WAQTD DETAILS OF AN EMP REPORTING TO JONES.
SELECT *
FROM SCOTT.EMP
                WHERE MGR IN
               (SELECT EMPNO
                FROM SCOTT.EMP
                WHERE ENAME = 'JONES');


--10  WAQTD LOCATION OF MARTIN'S MANAGER.
SELECT LOC ,DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(
              SELECT DEPTNO
              FROM SCOTT.EMP
              WHERE EMPNO IN (SELECT  MGR
                           FROM SCOTT.EMP
                           WHERE ENAME = 'MARTIN'));


--11 WAQTD NUMBER OF EMP'S REPORTING TO FORD
SELECT COUNT(*)
FROM SCOTT.EMP
                WHERE MGR IN
               (SELECT EMPNO
                FROM SCOTT.EMP
                WHERE ENAME = 'FORD');

--12 WAQTD COMMISION OF BLAKE'S MANAGER'S MANAGER
SELECT COMM
FROM SCOTT.EMP
WHERE  EMPNO IN(SELECT MGR
                 FROM SCOTT.EMP 
                 WHERE EMPNO IN
                      (SELECT MGR
                      FROM SCOTT.EMP
                      WHERE ENAME = 'BLAKE'));

--13 WAQTD DEPARTMENT NAME OF CLARK'S MANAGER
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                  FROM SCOTT.EMP
                  WHERE EMPNO IN(SELECT MGR
                                 FROM SCOTT.EMP
                                 WHERE ENAME = 'CLARK'))

--14  WAQTD LOCATION OF SCOTT'S MANAGER
SELECT LOC
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                  FROM SCOTT.EMP
                  WHERE EMPNO IN(SELECT MGR
                                 FROM SCOTT.EMP
  
                               WHERE ENAME = 'SCOTT'))

--15  WAQTD DEPTNO OF MILLER'S MANAGER.
SELECT DEPTNO
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT  MGR
        FROM SCOTT.EMP
        WHERE ENAME = 'MILLER')

--16  WAQTD TOTAL SALARY GIVEN TO WARD'S MANAGER'S 
--DEPTNO. 
SELECT SUM(SAL)
 FROM SCOTT.EMP
  WHERE DEPTNO IN
    (SELECT DEPTNO 
    FROM SCOTT.EMP
    WHERE EMPNO IN
    (SELECT MGR
          FROM SCOTT.EMP
      WHERE ENAME = 'WARD'))

--17 WAQTD MINIMUM SALARY GIVEN TO TURNER'S MANAGER'S 
--DEPTNO.
SELECT MIN(SAL)
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
WHERE EMPNO IN(SELECT  MGR
        FROM SCOTT.EMP
        WHERE ENAME = 'TURNER'));

--18 WAQTD AVERAGE SALARY GIVEN TO JONE'S MANAGER'S 
--DEPTNO.
SELECT AVG(SAL)
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
WHERE EMPNO IN(SELECT  MGR
        FROM SCOTT.EMP
        WHERE ENAME = 'JONES'));

--19  WAQTD NUMBER OF EMP'S PRESENT IN JAMES MANAGER'S 
--DEPTNO. 
SELECT COUNT(*)
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
WHERE EMPNO IN(SELECT  MGR
        FROM SCOTT.EMP
        WHERE ENAME = 'JAMES'));

--20 WAQTD FIRST FIVE RECORDS FROM EMP TABLE.
SELECT *
FROM SCOTT.EMP
HAVING COUNT(*) = 5;