SELECT * 
FROM SCOTT.EMP
WHERE  SAL < 
     ( SELECT  SAL 
      FROM SCOTT.EMP 
      WHERE ENAME = 'KING' );

      SELECT *
      FROM SCOTT.EMP
      WHERE JOB IN ( SELECT JOB 
                     FROM SCOTT.EMP
                     WHERE ENAME = 'FORD')  ;



    SELECT * 
    FROM SCOTT.EMP
    WHERE DEPTNO IN( SELECT DEPTNO 
                    FROM SCOTT.EMP
                    WHERE ENAME ='KING' 
    );

SELECT * FROM SCOTT.EMP
WHERE HIREDATE > (SELECT HIREDATE 
                  FROM SCOTT.EMP
                  WHERE  ENAME = 'WARD');


SELECT ENAME 
FROM SCOTT.EMP 
WHERE JOB = 'SALESMAN' AND
     SAL < (SELECT SAL
           FROM SCOTT.EMP
           WHERE ENAME ='MARTIN');

    --6
    SELECT * FROM SCOTT.EMP
    WHERE SAL >(SELECT SAL FROM SCOTT.EMP
               WHERE ENAME = 'JAMES') AND
               SAL <(SELECT SAL FROM SCOTT.EMP
               WHERE ENAME = 'JONES');

    --7
    SELECT ENAME ,SAL 
    FROM SCOTT.EMP 
    WHERE SAL < (SELECT SAL FROM SCOTT.EMP
                  WHERE ENAME = 'KING');

--8
SELECT ENAME ,SAL 
FROM SCOTT.EMP 
    WHERE SAL < (SELECT SAL FROM SCOTT.EMP
                  WHERE ENAME = 'ADAMS');
 --9
 SELECT ENAME ,DEPTNO
 FROM SCOTT.EMP
 WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
               WHERE  ENAME = 'JONES');

        --10
        SELECT ENAME ,JOB
        FROM SCOTT.EMP
        WHERE JOB IN(SELECT JOB 
        FROM SCOTT.EMP
        WHERE ENAME ='JAMES');

        --11
        SELECT EMPNO ,ENAME ,SAL*12 AS ANNUAL_SAL
        FROM SCOTT.EMP
        WHERE SAL*12 > (SELECT SAL*12 AS ANNUALSAL
                          FROM SCOTT.EMP
                          WHERE ENAME ='WARD');

--12
SELECT ENAME ,HIREDATE 
FROM SCOTT.EMP
WHERE HIREDATE <(SELECT HIREDATE 
                   FROM SCOTT.EMP
                   WHERE ENAME = 'TURNER');

--13
SELECT ENAME ,HIREDATE 
FROM SCOTT.EMP
WHERE HIREDATE >(SELECT HIREDATE 
                   FROM SCOTT.EMP
                   WHERE JOB = 'PRESIDENT');
                

SELECT  ENAME ,SAL 
FROM SCOTT.EMP
WHERE SAL <(SELECT SAL FROM SCOTT.EMP
            WHERE EMPNO = 7839);

--15
SELECT * 
FROM SCOTT.EMP 
WHERE  HIREDATE <(SELECT HIREDATE
                  FROM SCOTT.EMP
                   WHERE ENAME = 'MILLER');

--16
SELECT *
FROM SCOTT.EMP
WHERE SAL > (SELECT SAL
              FROM SCOTT.EMP
              WHERE ENAME = 'ALLEN');

--17
SELECT COUNT(*)
FROM SCOTT.EMP
WHERE  HIREDATE >(SELECT HIREDATE
                  FROM SCOTT.EMP
                   WHERE ENAME = 'KING');
        
--18
SELECT SUM(SAL)
FROM SCOTT.EMP
WHERE DEPTNO IN (SELECT DEPTNO
                 FROM SCOTT.EMP
                 WHERE ENAME ='WARD');

--19
SELECT *
FROM SCOTT.EMP
WHERE DEPTNO = 20 AND
     JOB IN(SELECT JOB
            FROM SCOTT.EMP
            WHERE  ENAME = 'SMITH');

--20
SELECT ENAME ,SAL
FROM SCOTT.EMP
WHERE SAL >(SELECT SAL FROM SCOTT.EMP
             WHERE ENAME = 'MILLER') AND
             SAL <(SELECT SAL FROM SCOTT.EMP
             WHERE ENAME = 'ALLEN');

--21
SELECT ENAME ,SAL
FROM SCOTT.EMP
WHERE SAL BETWEEN 1000 AND 3000; 

--22
SELECT * FROM SCOTT.EMP
WHERE DEPTNO = 20 AND
 JOB IN (SELECT JOB 
 FROM SCOTT.EMP 
 WHERE ENAME = 'SMITH');

 --23
 SELECT * FROM SCOTT.EMP
 WHERE JOB = 'MANAGER'
 AND DEPTNO IN(SELECT DEPTNO
                    FROM SCOTT.EMP
                    WHERE ENAME ='TURNER');

--24
SELECT ENAME, HIREDATE FROM SCOTT.EMP
WHERE HIREDATE > '31-DEC-1980' AND
      HIREDATE <(SELECT HIREDATE 
                  FROM SCOTT.EMP
                  WHERE ENAME = 'KING');

--25
SELECT ENAME ,SAL, SAL*6 AS ANNUAL_SAL
FROM SCOTT.EMP
WHERE  SAL < (SELECT SAL 
                FROM SCOTT.EMP
                WHERE ENAME = 'BLAKE')  OR 
                SAL > 3500;